### PR TITLE
Support Idea 2019.1.3

### PR DESCRIPTION
**Pull request by vbmacher**
Hello, this plugin is still quite useful and it's pity I don't see new updates. With new versions of IDEA (in upcoming 2019.2 EAP for example), this plugin fails. Since I want to continue using the plugin, I'd like to help with updating/maintaining it.

I have tried to update versions of the IDEA in SBT build, but I wasn't successful. One reason is that I don't know SBT well, also the [sbt-idea-plugin](https://github.com/JetBrains/sbt-idea-plugin) is very poorly documented and seems very complicated to me.

If you would insist on keeping SBT, fine, but with this PR I suggest another solution using Gradle. Setup was really painless and simple. I believe this improves the simplicity for updating also for the future. Also, I found that the [official guide](https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started.html) on IDEA plugin development suggests using either Gradle or Plugin DevKit.

This PR is and update for IDEA version 2019.1.3.

What I think as useful TODO to consider automating the publishing of the plugin.

### CODE REVIEW

**Comment by abdelrahmanmohamed** [comment]
@danielwegener  when you will support the latest versions, and merge this one :D

**Comment by jiminhsieh** [comment]
@danielwegener Could you merge this one? :) A lot of developers rely on it. Thanks.

**Comment by danielwegener** [comment]
Thanks for your PR! I am happy to get rid of this sbt plugin. It never worked for me as I would have liked it.

I'd be happy if you would pick up the maintenance since I've moved on and have little contact with this stack anymore. I'd also recommend everyone else to avoid the cucumber-scala api. But it seems to be useful for you so yeah why not. I think the easiest would be that you fork this repo with your account and I'll provide you publish permissions in the jenkins plugin repository and change the code-link and issue-tracking to your fork.

Regarding the changes: I think the dependency to scala-library should not be in implementation but rather compileOnly scope (the scala libarary is already shipped by the intellij scala plugin).But we can fix that on master with the migration for the recent intellij.

**Comment by vbmacher** [comment]
Thanks for merging. Regarding the takeover, I am still willing to do it. However, depending what you want to do with this repository, I see there two options:

1. One possibility is to do as you said: fork, and I will continue under the same project name and this repository will become "outdated" or act more like an archive.

2. The other option is to transfer the ownership of this repository to me (https://help.github.com/en/github/administering-a-repository/transferring-a-repository). You would become a contributor automatically but I will gain owner rights. The project then can continue going on.

I am generally fine with both options, but in the first case this repo would need to be updated to say it's stopped being active, etc. For that reason I think it would be maybe better to go with the second option (transfer it).

In case of any private conversation (sharing credentials etc.) you can write me on my email which you can find in my profile.

Regarding the gradle changes you propose, I totally agree. However there need to be done more than just this, since the Jetbrain's APIs changed.. So I agree to do it separately.

**Comment by danielwegener** [comment]
@vbmacher I've already migrated everything to 2019.3.2 on master and the most recent gradle plugin version. I wasn't aware about the repo transfer feature, I just wanted to avoid having it evolve under my personal account without being in the loop at all - no offence - so I'd be fine with a transfer. Right now I am trying to get my access to the jenkins plugin repository back. Somehow during the introduction of jenkins hub, I've lost access to the plugin there :)

**Comment by vbmacher** [comment]
Perfect (about the changes). And I hope you you'll manage to restore the access :))

**Comment by danielwegener** [comment]
@vbmacher  I have added you to the plugin contributors in the jetbrains plugin repository. Last time I've tried I could not find you but hopefully I now have added the right account.

**Comment by vbmacher** [comment]
Thank you. Last time maybe we didn't meet in time when you tried to do it and when I was just creating the account :)

**Pull request merged**
